name: test-post-run-input

inputs:
  test-input:
    default: 'default'
    description: test input
    required: false

runs:
  using: composite
  steps:
    - name: Run this action
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          echo "input is: ${{ inputs.test-input }}"
        post: |
          echo "First post"
          echo "input is: ${{ inputs.test-input }}"
